[lint]
extend-ignore = [
    "BLE001",
    "TRY201",
    "DTZ001",
    "DTZ005",
    "SIM117",
    "RUF059",
    "I001",
    "PLR0402",
    "S110",
    "PLR1722",
    "RUF013",
    "UP006",
    "UP045",
    "UP035",
    "PERF102",
    "SIM102",
    "UP012",
    "EXE001",
    "C401",
    "SIM118",
    "UP007",
    "UP024",
    "PIE790",
    "G201",
    "PLW1510",
    "TRY002",
    "PYI041",
    "TRY004",
    "S102",
    "S112",
    "SIM103",
    "C414",
    "RUF012",
    "LOG014",
    "C408",
    "DTZ006",
    "RUF019",
    "LOG015",
    "PLW0602"
]
